using System.Text.Json;
using System.Text.Json.Serialization;

namespace MahjongHater.Core.Policy;

// Measured deal-in rates against ONE seat in riichi, by tile class and that seat's live
// suji count, plus the multipliers the danger model applies on top. Generated by
// tools/make_deal_in_rates.py from docs/research/*.csv into resources/policy/deal_in_rates.json
// (ships next to the dll, embedded as the fallback, like the layout). No number that belongs in
// the JSON is ever hard-coded here.
public sealed class DealInRateTable
{
    public const string DefaultResourcePath = "resources/policy/deal_in_rates.json";

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true,
        ReadCommentHandling = JsonCommentHandling.Skip,
        AllowTrailingCommas = true,
    };

    private static readonly Lazy<DealInRateTable> EmbeddedTable = new(() => Parse(ReadEmbedded()));

    private readonly Dictionary<string, Dictionary<int, Row>> numbers;
    private readonly Dictionary<string, Row?[]> plainHonors;
    private readonly Dictionary<string, Row?[]> doraHonors;
    private readonly double[] honorShape;

    private DealInRateTable(Dictionary<string, Dictionary<int, Row>> numbers,
        Dictionary<string, Row?[]> plainHonors, Dictionary<string, Row?[]> doraHonors, double[] honorShape, Multipliers multipliers)
    {
        this.numbers = numbers;
        this.plainHonors = plainHonors;
        this.doraHonors = doraHonors;
        this.honorShape = honorShape;
        this.Multipliers = multipliers;
    }

    public static DealInRateTable Default => EmbeddedTable.Value;

    public Multipliers Multipliers { get; }

    // Number tile classes as the sheet names them.
    public enum NumberClass
    {
        NonSuji,
        Suji,            // 1-3 / 7-9 with the matching suji genbutsu (not the riichi tile)
        RiichiSuji,      // same, but the genbutsu is the riichi declaration tile
        HalfSuji,        // 4-6 with one side safe
        HalfSujiRiichi,  // 4-6, the safe side is the riichi tile
        Nakasuji,        // 4-6 with both sides safe
        NakasujiRiichi,  // 4-6 both sides safe, one of them the riichi tile
    }

    public enum HonorClass
    {
        Guest,   // not a yakuhai for the target seat
        Seat,
        Round,
        Double,  // seat and round wind
        Dragon,
    }

    // P(deal in) for a number tile of this class and rank against a seat with `liveSuji`
    // suji still alive. Missing cells fall back to the nearest sampled neighbour, then the total.
    public double Number(NumberClass cls, int number, int liveSuji)
    {
        var key = cls switch
        {
            NumberClass.NonSuji => "nonSuji",
            NumberClass.Suji => "suji",
            NumberClass.RiichiSuji => "riichiSuji",
            NumberClass.HalfSuji => "halfSuji",
            NumberClass.HalfSujiRiichi => "halfSujiRiichi",
            NumberClass.Nakasuji => "nakasuji",
            NumberClass.NakasujiRiichi => "nakasujiRiichi",
            _ => throw new ArgumentOutOfRangeException(nameof(cls)),
        };
        if (!this.numbers.TryGetValue(key, out var byNumber) || !byNumber.TryGetValue(number, out var row))
            throw new KeyNotFoundException($"deal-in table has no row for {key} {number}");
        return row.At(liveSuji);
    }

    public double Honor(HonorClass cls, int visibleCopies, bool isDora, int liveSuji)
    {
        var key = cls switch
        {
            HonorClass.Guest => "guest",
            HonorClass.Seat => "seat",
            HonorClass.Round => "round",
            HonorClass.Double => "double",
            HonorClass.Dragon => "dragon",
            _ => throw new ArgumentOutOfRangeException(nameof(cls)),
        };
        var copies = Math.Clamp(visibleCopies, 0, 3);
        var plain = this.plainHonors[key][copies]
            ?? throw new KeyNotFoundException($"deal-in table has no honor row for {key} {copies}");
        // Honor rows are thin per live-suji column: level from the row's total, shape from
        // the best-sampled honor row (generator: honorShape), dora as a ratio of totals.
        var rate = plain.Total;
        if (isDora && this.doraHonors.TryGetValue(key, out var doraRows) && doraRows[copies] is { Total: > 0 } dora)
            rate = dora.Total;
        var column = Math.Clamp(18 - liveSuji, 0, this.honorShape.Length - 1);
        return this.honorShape.Length > 0 ? rate * this.honorShape[column] : rate;
    }

    public static DealInRateTable LoadDefault(string? assemblyDirectory)
    {
        if (assemblyDirectory is not null)
        {
            var path = Path.Combine(assemblyDirectory, DefaultResourcePath);
            if (File.Exists(path))
                return Parse(File.ReadAllText(path));
        }

        return Default;
    }

    public static DealInRateTable Parse(string json)
    {
        var dto = JsonSerializer.Deserialize<Dto>(json, JsonOptions)
                  ?? throw new InvalidDataException("deal_in_rates.json is empty.");
        var numbers = new Dictionary<string, Dictionary<int, Row>>(StringComparer.OrdinalIgnoreCase);
        foreach (var (cls, byNumber) in dto.Numbers ?? throw new InvalidDataException("deal_in_rates.json: numbers missing"))
        {
            var rows = new Dictionary<int, Row>();
            foreach (var (number, row) in byNumber)
                rows[int.Parse(number, System.Globalization.CultureInfo.InvariantCulture)] = Row.From(row);
            numbers[cls] = rows;
        }

        static Dictionary<string, Row?[]> Honors(Dictionary<string, RowDto?[]>? group)
        {
            var result = new Dictionary<string, Row?[]>(StringComparer.OrdinalIgnoreCase);
            foreach (var (cls, rows) in group ?? throw new InvalidDataException("deal_in_rates.json: honors missing"))
                result[cls] = rows.Select(r => r is null ? null : Row.From(r)).ToArray();
            return result;
        }

        var honors = dto.Honors ?? throw new InvalidDataException("deal_in_rates.json: honors missing");
        var multipliers = dto.Multipliers ?? throw new InvalidDataException("deal_in_rates.json: multipliers missing");
        if (multipliers.VisibleCopies is not { Length: 4 })
            throw new InvalidDataException("deal_in_rates.json: multipliers.visibleCopies needs 4 entries");
        return new DealInRateTable(numbers, Honors(honors.Plain), Honors(honors.Dora), dto.HonorShape ?? [], multipliers);
    }

    public static string ReadEmbedded()
    {
        var asm = typeof(DealInRateTable).Assembly;
        var name = asm.GetManifestResourceNames().FirstOrDefault(n => n.EndsWith("deal_in_rates.json", StringComparison.OrdinalIgnoreCase))
                   ?? throw new InvalidDataException("Embedded deal_in_rates.json resource missing.");
        using var stream = asm.GetManifestResourceStream(name)!;
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }

    private sealed class Row
    {
        private double?[] byLiveSuji = [];

        public double Total { get; private init; }

        public static Row From(RowDto dto) => new()
        {
            Total = dto.Total ?? 0,
            byLiveSuji = dto.ByLiveSuji ?? [],
        };

        // Column i holds 18 - i live suji. Walk outward from the requested column to the
        // nearest sampled one; an empty row answers with its total.
        public double At(int liveSuji)
        {
            if (this.byLiveSuji.Length == 0)
                return this.Total;
            var centre = Math.Clamp(18 - liveSuji, 0, this.byLiveSuji.Length - 1);
            for (var d = 0; d < this.byLiveSuji.Length; d++)
            {
                if (centre - d >= 0 && this.byLiveSuji[centre - d] is { } lo)
                    return lo;
                if (centre + d < this.byLiveSuji.Length && this.byLiveSuji[centre + d] is { } hi)
                    return hi;
            }

            return this.Total;
        }
    }

    private sealed record Dto(
        Dictionary<string, Dictionary<string, RowDto>>? Numbers,
        HonorsDto? Honors,
        double[]? HonorShape,
        Multipliers? Multipliers);

    private sealed record HonorsDto(Dictionary<string, RowDto?[]>? Plain, Dictionary<string, RowDto?[]>? Dora);

    private sealed record RowDto(double? Total, double?[]? ByLiveSuji);
}

// Multipliers layered on the measured rates (Fukuchi ch. 2 and Riichi Book 1 ch. 8).
public sealed record Multipliers
{
    public double EarlyOutside { get; init; } = 0.6;

    public double DoraTile { get; init; } = 1.3;

    public double DoraTerminal { get; init; } = 1.7;

    public double DoraNeighbour { get; init; } = 1.1;

    public double OneChanceEarly { get; init; } = 0.75;

    public double OneChanceLate { get; init; } = 1.0;

    public double DoubleOneChance { get; init; } = 0.5;

    // At or below this many live suji a one-chance is "late" (the missing copy is likely held).
    public int OneChanceLateLiveSuji { get; init; } = 8;

    // By copies of the number tile already visible (fewer shanpon / tanki shapes remain).
    [JsonPropertyName("visibleCopies")]
    public double[] VisibleCopies { get; init; } = [1.0, 0.95, 0.85, 0.6];

    // A third visible honor is 0 % in the data; keep a sliver for kokushi until it is impossible.
    public double HonorKokushiFloor { get; init; } = 0.002;
}
